### ISSUE TITLE
# TODO

### ISSUE THREAD

**Issue by csr000** [csr000/test#1]
- [ ] add loading when a query is made
- [ ] animate with animate.css
- [ ] get & display total number of employees 
- [ ] get & display total number of attendance
